### PR TITLE
Add read compacted option to consumer options.

### PR DESCRIPTION
**Pull request by mkaufmaner**

### CODE REVIEW

**Comment by hrsakai** [comment]
retest this please

**Comment by hrsakai** [comment]
@mkaufmaner 
Could you add `readCompacted` option to the [ReaderConfig](https://github.com/apache/pulsar-client-node/blob/master/src/ReaderConfig.cc) class as well?

You can use `pulsar_reader_configuration_set_read_compacted()`.
https://github.com/apache/pulsar/blob/v2.4.2/pulsar-client-cpp/lib/c/c_ReaderConfiguration.cc#L81
https://github.com/apache/pulsar/blob/v2.4.2/pulsar-client-go/pulsar/c_reader.go#L106

**Comment by mkaufmaner** [comment]
> @mkaufmaner
> Could you add `readCompacted` option to the [ReaderConfig](https://github.com/apache/pulsar-client-node/blob/master/src/ReaderConfig.cc) class as well?
> 
> You can use `pulsar_reader_configuration_set_read_compacted()`.
> https://github.com/apache/pulsar/blob/v2.4.2/pulsar-client-cpp/lib/c/c_ReaderConfiguration.cc#L81
> https://github.com/apache/pulsar/blob/v2.4.2/pulsar-client-go/pulsar/c_reader.go#L106

Will do!

Also, could you elaborate on what you mean by "retest this please"?

**Comment by hrsakai** [comment]
> could you elaborate on what you mean by "retest this please"?

"retest this please" is the trigger for [Jenkins precommit job](https://builds.apache.org/job/pulsar_precommit_client_node/).
After commenting "retest this please", jenkins will start the precommit job.
The precommit job did not run for some reason, so I commented "retest this please".

**Comment by hrsakai** [comment]
retest this please

**Comment by hrsakai** [comment]
@mkaufmaner 
Thank you for your contribution!

**Comment by mkaufmaner** [comment]
> @mkaufmaner
> Thank you for your contribution!

Anytime!  Thank you for your review as well!

**Pull request merged**
