### PR TITLE
Adds NodeJS version to the readme file

### PR DESCRIPTION
**Pull request by pikitgb**

### CODE REVIEW

**Comment by massakam** [comment]
In my environment, the package can be installed and works properly even if the Node.js version is 10.x.
```sh
$ node -v

v10.16.3

$ npm -v

6.9.0

$ rpm -qa | grep 'apache-pulsar-client'

apache-pulsar-client-2.4.2-1.x86_64
apache-pulsar-client-devel-2.4.2-1.x86_64

$ npm install pulsar-client

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> pulsar-client@1.1.0 install /home/massakam/nodejs/node_modules/pulsar-client
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://pulsar.apache.org/docs/en/client-libraries-cpp/libpulsar-v1.1.0-node-v64-linux-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for pulsar-client@1.1.0 and node@10.16.3 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
make: Entering directory `/home/massakam/nodejs/node_modules/pulsar-client/build'
  CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
  AR(target) Release/obj.target/../node-addon-api/src/nothing.a
  COPY Release/nothing.a
  CXX(target) Release/obj.target/Pulsar/src/addon.o
  CXX(target) Release/obj.target/Pulsar/src/Message.o
  CXX(target) Release/obj.target/Pulsar/src/MessageId.o
  CXX(target) Release/obj.target/Pulsar/src/Authentication.o
  CXX(target) Release/obj.target/Pulsar/src/Client.o
  CXX(target) Release/obj.target/Pulsar/src/Producer.o
  CXX(target) Release/obj.target/Pulsar/src/ProducerConfig.o
  CXX(target) Release/obj.target/Pulsar/src/Consumer.o
  CXX(target) Release/obj.target/Pulsar/src/ConsumerConfig.o
  CXX(target) Release/obj.target/Pulsar/src/Reader.o
  CXX(target) Release/obj.target/Pulsar/src/ReaderConfig.o
  SOLINK_MODULE(target) Release/obj.target/Pulsar.node
  COPY Release/Pulsar.node
make: Leaving directory `/home/massakam/nodejs/node_modules/pulsar-client/build'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN pulsar-sample@1.0.0 No description
npm WARN pulsar-sample@1.0.0 No repository field.

+ pulsar-client@1.1.0
added 122 packages from 130 contributors and audited 122 packages in 20.911s
found 0 vulnerabilities
```

**Comment by pikitgb** [comment]
uhm based on your folder structure it doesn't look like you are running Catalina 10.15/Mac.

**Comment by massakam** [comment]
Yes, my environment is CentOS 7.

**Comment by equanz** [comment]
My environment is macOS 10.15.4, but it seems that be able to install pulsar-client.

```
$ sudo n 10.16.3
   installed : v10.16.3 (with npm 6.9.0)

$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.15.4
BuildVersion:   19E287

$ which g++
/usr/bin/g++

$ node -v
v10.16.3

$ npm -v
6.9.0

$ brew info libpulsar
libpulsar: stable 2.5.1 (bottled)
Apache Pulsar C++ library
https://pulsar.apache.org/
/usr/local/Cellar/libpulsar/2.5.1 (53 files, 18.6MB) *
  Poured from bottle on 2020-04-23 at 08:14:26
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/libpulsar.rb
==> Dependencies
Build: cmake ✘, pkg-config ✔
Required: boost ✔, openssl@1.1 ✔, protobuf ✘, snappy ✔, zstd ✔
==> Analytics
install: 187 (30 days), 483 (90 days), 1,684 (365 days)
install-on-request: 188 (30 days), 484 (90 days), 1,683 (365 days)
build-error: 0 (30 days)

$ npm install pulsar-client
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> pulsar-client@1.1.0 install /Users/yumizush/Desktop/pcn/node_modules/pulsar-client
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://pulsar.apache.org/docs/en/client-libraries-cpp/libpulsar-v1.1.0-node-v64-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for pulsar-client@1.1.0 and node@10.16.3 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
  CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
  LIBTOOL-STATIC Release/nothing.a
  CXX(target) Release/obj.target/Pulsar/src/addon.o
In file included from ../src/addon.cc:23:
In file included from ../src/Producer.h:24:
In file included from /usr/local/include/pulsar/c/client.h:23:
/usr/local/include/pulsar/c/client_configuration.h:147:15: warning: 'const' type qualifier on return type has no effect [-Wignored-qualifiers]
PULSAR_PUBLIC const unsigned int pulsar_client_configuration_get_stats_interval_in_seconds(
              ^~~~~~
1 warning generated.
  CXX(target) Release/obj.target/Pulsar/src/Message.o
  CXX(target) Release/obj.target/Pulsar/src/MessageId.o
  CXX(target) Release/obj.target/Pulsar/src/Authentication.o
  CXX(target) Release/obj.target/Pulsar/src/Client.o
In file included from ../src/Client.cc:20:
In file included from ../src/Client.h:24:
In file included from /usr/local/include/pulsar/c/client.h:23:
/usr/local/include/pulsar/c/client_configuration.h:147:15: warning: 'const' type qualifier on return type has no effect [-Wignored-qualifiers]
PULSAR_PUBLIC const unsigned int pulsar_client_configuration_get_stats_interval_in_seconds(
              ^~~~~~
1 warning generated.
  CXX(target) Release/obj.target/Pulsar/src/Producer.o
In file included from ../src/Producer.cc:20:
In file included from ../src/Producer.h:24:
In file included from /usr/local/include/pulsar/c/client.h:23:
/usr/local/include/pulsar/c/client_configuration.h:147:15: warning: 'const' type qualifier on return type has no effect [-Wignored-qualifiers]
PULSAR_PUBLIC const unsigned int pulsar_client_configuration_get_stats_interval_in_seconds(
              ^~~~~~
1 warning generated.
  CXX(target) Release/obj.target/Pulsar/src/ProducerConfig.o
  CXX(target) Release/obj.target/Pulsar/src/Consumer.o
In file included from ../src/Consumer.cc:20:
In file included from ../src/Consumer.h:24:
In file included from /usr/local/include/pulsar/c/client.h:23:
/usr/local/include/pulsar/c/client_configuration.h:147:15: warning: 'const' type qualifier on return type has no effect [-Wignored-qualifiers]
PULSAR_PUBLIC const unsigned int pulsar_client_configuration_get_stats_interval_in_seconds(
              ^~~~~~
../src/Consumer.cc:112:22: warning: private field 'cConsumer' is not used [-Wunused-private-field]
  pulsar_consumer_t *cConsumer;
                     ^
2 warnings generated.
  CXX(target) Release/obj.target/Pulsar/src/ConsumerConfig.o
In file included from ../src/ConsumerConfig.cc:21:
In file included from ../src/Consumer.h:24:
In file included from /usr/local/include/pulsar/c/client.h:23:
/usr/local/include/pulsar/c/client_configuration.h:147:15: warning: 'const' type qualifier on return type has no effect [-Wignored-qualifiers]
PULSAR_PUBLIC const unsigned int pulsar_client_configuration_get_stats_interval_in_seconds(
              ^~~~~~
1 warning generated.
  CXX(target) Release/obj.target/Pulsar/src/Reader.o
In file included from ../src/Reader.cc:21:
In file included from ../src/Reader.h:24:
In file included from /usr/local/include/pulsar/c/client.h:23:
/usr/local/include/pulsar/c/client_configuration.h:147:15: warning: 'const' type qualifier on return type has no effect [-Wignored-qualifiers]
PULSAR_PUBLIC const unsigned int pulsar_client_configuration_get_stats_interval_in_seconds(
              ^~~~~~
1 warning generated.
  CXX(target) Release/obj.target/Pulsar/src/ReaderConfig.o
  SOLINK_MODULE(target) Release/Pulsar.node
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN pcn@1.0.0 No description
npm WARN pcn@1.0.0 No repository field.

+ pulsar-client@1.1.0
added 122 packages from 130 contributors and audited 122 packages in 40.915s
found 0 vulnerabilities
```

**Pull request closed without merging**
