### PR TITLE
Update C++ client version and compatiblity table to v2.10.1

### PR DESCRIPTION
**Pull request by equanz**
### Motivation

Relates to https://github.com/apache/pulsar-client-node/pull/215 and https://github.com/apache/pulsar/pull/15508

According to https://github.com/apache/pulsar-client-node/pull/215 , "double callback segfault" issue was fixed in https://github.com/apache/pulsar/pull/15508 .
The https://github.com/apache/pulsar/pull/15508 fix was released as v2.10.1 ( https://github.com/apache/pulsar/commit/fa05a850e7356b42591fc04506496026c96ad878 ).

We should use the fixed version of C++ client.

### Modifications

* Modify `pulsar-version.txt` to use C++ client version to v2.10.1 in CI
* Update compatibility table

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)

### Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by equanz** [comment]
In `apachepulsar/pulsar-build:ubuntu-16.04` image, use `-Xlog:gc*:logs/pulsar_gc_%p.log:time,uptime:filecount=10,filesize=20M` option for runtime.
https://github.com/apache/pulsar/blob/v2.10.1/conf/pulsar_env.sh#L50-L58

However, pulsar command uses `JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64` in runtime.
https://hub.docker.com/layers/apachepulsar/pulsar-build/ubuntu-16.04/images/sha256-57174595e685002c0e4ce768361af8c10fcf30310f466966c3f8663a8638e4b7?context=explore

```
Unrecognized option: -Xlog:gc*:logs/pulsar_gc_%p.log:time,uptime:filecount=10,filesize=20M
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
(The script file was fixed in https://github.com/apache/pulsar/pull/14711 .)

I updated the docker image tag to `ubuntu-20.04` to avoid this issue.
`JAVA_HOME` was not set in `ubuntu-20.04` image.
https://hub.docker.com/layers/apachepulsar/pulsar-build/ubuntu-20.04/images/sha256-5f50d029fa6ba5a1d410faf7d4d0539200246572a1459cb6e3cc32219300f591?context=explore



Also, I modified test scripts to fix the below issue.
```
fatal: unsafe repository ('/pulsar-client-node' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /pulsar-client-node
```

**Comment by equanz** [comment]
It seems https://github.com/apache/pulsar/pull/15009 causes the following errors. This change was released as `v2.9.3` and `v2.10.1` .
I modified test codes to address this change.

```
> jest --verbose

Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
PASS tests/end_to_end.test.js (9.466 s)
  End To End
    ✓ Produce/Consume (582 ms)
    ✓ negativeAcknowledge (2381 ms)
    ✓ getRedeliveryCount (310 ms)
    ✓ Produce/Consume Listener (103 ms)
    ✓ Produce/Read Listener (98 ms)
    ✓ acknowledgeCumulative (1091 ms)
    ✓ subscriptionInitialPosition (125 ms)
    ✓ Produce/Read (92 ms)
    ✓ Produce-Delayed/Consume (3100 ms)
    ✓ Produce/Consume/Unsubscribe (141 ms)
    ✓ Produce/Read (Compression) (66 ms)
    ✓ Produce/Consume-Pattern (134 ms)
    ✓ Produce/Consume-Multi-Topic (140 ms)
    ✓ Produce/Consume and validate MessageId (224 ms)
    ✓ Basic produce and consume encryption (115 ms)
    ✓ Produce/Consume/Read/IsConnected (17 ms)

FAIL tests/consumer.test.js
  Consumer
    Create
      ✓ No Topic (1 ms)
      ✓ Not String Topic (1 ms)
      ✓ Not String TopicsPattern
      ✓ Not Array Topics
      ✓ Not String in Array Topics (1 ms)
      ✓ No Subscription
      ✓ Not String Subscription (1 ms)
      ✕ Not Exist Tenant (18 ms)
      ✕ Not Exist Namespace (4 ms)
      ✓ Not Positive NAckRedeliverTimeout (1 ms)
    Close
      ✓ throws error on subsequent calls to close (55 ms)

  ● Consumer › Create › Not Exist Tenant

    expect(received).rejects.toThrow(expected)

    Expected substring: "Failed to create consumer: ConnectError"
    Received message:   "Failed to create consumer: BrokerMetadataError"

      103 |           ackTimeoutMs: 10000,
      104 |           nAckRedeliverTimeoutMs: 60000,
    > 105 |         })).rejects.toThrow('Failed to create consumer: ConnectError');
          |                     ^
      106 |       });
      107 |
      108 |       test('Not Exist Namespace', async () => {

      at Object.toThrow (node_modules/expect/build/index.js:285:22)
      at Object.<anonymous> (tests/consumer.test.js:105:21)

  ● Consumer › Create › Not Exist Namespace

    expect(received).rejects.toThrow(expected)

    Expected substring: "Failed to create consumer: ConnectError"
    Received message:   "Failed to create consumer: BrokerMetadataError"

      112 |           ackTimeoutMs: 10000,
      113 |           nAckRedeliverTimeoutMs: 60000,
    > 114 |         })).rejects.toThrow('Failed to create consumer: ConnectError');
          |                     ^
      115 |       });
      116 |
      117 |       test('Not Positive NAckRedeliverTimeout', async () => {

      at Object.toThrow (node_modules/expect/build/index.js:285:22)
      at Object.<anonymous> (tests/consumer.test.js:114:21)

FAIL tests/producer.test.js
  Producer
    Create
      ✓ No Topic (1 ms)
      ✓ Not String Topic (1 ms)
      ✕ Not Exist Tenant (3 ms)
      ✕ Not Exist Namespace (2 ms)
      ✓ Automatic Producer Name (42 ms)
      ✓ Explicit Producer Name (6 ms)
      ✓ Topic Name (6 ms)

  ● Producer › Create › Not Exist Tenant

    expect(received).rejects.toThrow(expected)

    Expected substring: "Failed to create producer: ConnectError"
    Received message:   "Failed to create producer: BrokerMetadataError"

      56 |           sendTimeoutMs: 30000,
      57 |           batchingEnabled: true,
    > 58 |         })).rejects.toThrow('Failed to create producer: ConnectError');
         |                     ^
      59 |       });
      60 |
      61 |       test('Not Exist Namespace', async () => {

      at Object.toThrow (node_modules/expect/build/index.js:285:22)
      at Object.<anonymous> (tests/producer.test.js:58:21)

  ● Producer › Create › Not Exist Namespace

    expect(received).rejects.toThrow(expected)

    Expected substring: "Failed to create producer: ConnectError"
    Received message:   "Failed to create producer: BrokerMetadataError"

      64 |           sendTimeoutMs: 30000,
      65 |           batchingEnabled: true,
    > 66 |         })).rejects.toThrow('Failed to create producer: ConnectError');
         |                     ^
      67 |       });
      68 |
      69 |       test('Automatic Producer Name', async () => {

      at Object.toThrow (node_modules/expect/build/index.js:285:22)
      at Object.<anonymous> (tests/producer.test.js:66:21)

PASS tests/reader.test.js
  Reader
    ✓ No Topic (1 ms)
    ✓ Not String Topic (1 ms)
    ✓ No StartMessageId (1 ms)
    ✓ Not StartMessageId as MessageId

Test Suites: 2 failed, 2 passed, 4 total
Tests:       4 failed, 34 passed, 38 total
Snapshots:   0 total
Time:        9.915 s
Ran all test suites.
```

**Review by k2la — APPROVED** [review]
LGTM

**Review by hrsakai — APPROVED** [review]
LGTM

**Pull request merged**
