### PR TITLE
fix: use pause and resume api to ensure orderly init listener->consumer

### PR DESCRIPTION
**Pull request by lipeining**

### CODE REVIEW

**Comment by lipeining** [comment]
#181

**Comment by massakam** [comment]
@lipeining Thank you for your contribution. The change looks good to me.

But why is the destination branch `branch-1.3` instead of `master`? Do you want v1.3.x with this patch to be released?

**Comment by rickyes** [comment]
> @lipeining Thank you for your contribution. The change looks good to me.
> 
> But why is the destination branch `branch-1.3` instead of `master`? Do you want v1.3.x with this patch to be released?

Hi, @massakam 

We are currently experiencing this issue in version `v1.3.x` by chance and would like to know more details about the cause, if you know the details could you please help us analyze it ?

**Comment by massakam** [comment]
@rickyes Details are explained in #181. Merging this PR should fix the issue.

**Review by massakam — APPROVED** [review]

**Comment by rickyes** [comment]
@massakam It is rather strange that we do not reproduce it locally, but only in specific network environments.

**Comment by massakam** [comment]
@rickyes This phenomenon does not always occur. It happens when `data->consumer` is accessed in the following part before it is initialized.
https://github.com/apache/pulsar-client-node/blob/50c090678ecedaa06e2c68ce1db3046655a9a075/src/Consumer.cc#L62-L65

Adding sleep to the following part will almost certainly reproduce this issue.
```diff
--- a/src/Consumer.cc
+++ b/src/Consumer.cc
@@ -23,6 +23,7 @@
 #include "MessageId.h"
 #include <pulsar/c/result.h>
 #include <atomic>
+#include <chrono>
 #include <thread>

 Napi::FunctionReference Consumer::constructor;
@@ -163,6 +164,7 @@ class ConsumerNewInstanceWorker : public Napi::AsyncWorker {
     Consumer *consumer = Consumer::Unwrap(obj);

     consumer->SetCConsumer(this->consumerWrapper);
+    std::this_thread::sleep_for(std::chrono::seconds(5));
     consumer->SetListenerCallback(this->listener);
     this->deferred.Resolve(obj);
   }
```

**Comment by rickyes** [comment]
@massakam Is it possible that the MessageListener was triggered before we triggered the callback subscribeCallback?

**Comment by massakam** [comment]
@rickyes I think this bug becomes apparent if the `MessageListener` is triggered before the `subscribeCallback` is completed.

**Comment by rickyes** [comment]
@massakam Sorry, I meant before the `subscribeCallback` was triggered and not before the `subscribeCallback` was completed.

**Comment by rickyes** [comment]
Because if it is possible to trigger the `MessageListener` before the `subscribeCallback` is triggered, this PR doesn't do much good.

**Comment by massakam** [comment]
@rickyes Sorry, [this comment](https://github.com/apache/pulsar-client-node/pull/182#issuecomment-986538154) is incorrect. It seems that `MessageListener` is not triggered until the execution of `subscribeCallback` is completed.

`subscribeCallback` is executed on the following line in the C++ client library. And the C++ client will not start receiving messages until this method completes.
https://github.com/apache/pulsar/blob/a54c6c003c626cb16d90200ad81dd3ec37be2133/pulsar-client-cpp/lib/ClientConnection.cc#L877

**Comment by rickyes** [comment]
@massakam LGTM, thank you for your patient answer~

**Pull request merged**
