### PR TITLE
docs: add typedoc to generate apidoc 

### PR DESCRIPTION
**Pull request by tisonkun**
This closes https://github.com/apache/pulsar/issues/19876.

image

Perhaps I'll pick this change to branch-1.8 and generate the first API docs for hosting on our website.

### Documentation

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)

- [ ] `doc-not-needed` 
(Please explain why)

- [x] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

**Review by BewareMyPower — COMMENTED** [review]
Could you add the docs for how to generate the API docs? (Though it's a simple command)

**Comment by tisonkun** [comment]
@BewareMyPower Make sense. I'll add one entry. Also I'll integrate this function to `apache/pulsar-siite/tools/pytools` and update the release guide (we should generate for feature releases).

**Comment by shibd** [comment]
> Perhaps I'll pick this change to branch-1.8 and generate the first API docs for hosting on our website.

Yes, I'll plan to release v1.8.2 next week. After this is merged, I'll cherry-pick this.

**Review by shibd — APPROVED** [review]

**Review by BewareMyPower — APPROVED** [review]

**Comment by tisonkun** [comment]
Merging...

Thanks for your review.

**Comment by momo-jun** [comment]
@tisonkun, what's the public URL to view the new API docs for Node.js clients? We may need to add this link to the client doc.

**Pull request merged**
