### PR TITLE
[feat] End-to-end encryption support for Reader

### LINKED ISSUE #276: [feature request] Reader support End-to-end Encryption
## Motivation

Only need to wrap the CPP client and expose the settings `CryptoKeyReader`

Depend on CPP client expose C API: https://github.com/apache/pulsar-client-cpp/issues/166

### PR DESCRIPTION
**Pull request by rbarbey**
Fixes #276 

### Motivation

With the underlying C library exposing the required reader config options for enabling encryption, the Node.js library can now also support end-to-end encryption when reading from a topic. 

### Modifications

- Added handling of config options required for encryption to work to the NAPI part
- Added those options to the type definition
- Added an example how to configure a Reader that reads from an encrypted topic
- Added tests

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change added tests and can be verified as follows:

- added integration test

### Documentation

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)

- [ ] `doc-not-needed` 
(Please explain why)

- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

I'm unsure what to check here since I've added an example how to create a Reader that's using encryption. But the compatibility matrix needs to be updated after this PR is merged.

### CODE REVIEW

**Comment by rbarbey** [comment]
The test failures in "Run unit tests" job look like intermittent errors to me because I didn't haven them in my fork PR. As for the "Build NAPI macos with CPP lib installed by Homebrew" job, It looks like `brew` still install `libpulsar` version 3.1.2 and not the current 3.2.0. Is there maybe some caching going on?

**Comment by rbarbey** [comment]
Done!

**Comment by RobertIndie** [comment]
The CI still uses the old version of the CPP lib: https://github.com/apache/pulsar-client-node/pull/328. But the libpulsar 3.2.0 has already been pushed to the homebrew: https://github.com/Homebrew/homebrew-core/pull/131064

I have pushed a PR to fix it: https://github.com/apache/pulsar-client-node/pull/328

**Comment by RobertIndie** [comment]
HI, @rbarbey , https://github.com/apache/pulsar-client-node/pull/328 has been merged. You can rebase this PR to get CI passed.

**Review by RobertIndie — APPROVED** [review]

**Comment by rbarbey** [comment]
Thanks @RobertIndie ! I just rebased

**Review by shibd — APPROVED** [review]

**Review by shibd — APPROVED** [review]

**Pull request merged**
