### PR TITLE
Use license-checker directly instead of grunt-license-report

### PR DESCRIPTION
**Pull request by massakam**
### Motivation

Executing `npm run license:report` in this repository will report the licenses of dependent modules to `report/licenses.html`. However, the [grunt-license-report](https://www.npmjs.com/package/grunt-license-report) module used by this command has not been maintained for nearly a decade, and the GitHub repository is a dead link. As a result, some modules with security vulnerabilities are installed by `grunt-license-report` dependencies.

### Modifications

Removed `grunt-license-report` from dev dependencies and added [license-checker](https://www.npmjs.com/package/license-checker) instead. `license-checker` has already been installed since `grunt-license-report` depends on it, but its version is 2.0.1 which is very old. Installing `license-checker` directly bumps its version to 25.0.1.

By the way, `license-checker` also hasn't been released in about 5 years, but it seems to be much more widely used than `grunt-license-report`.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Documentation

- [x] `doc-not-needed`

### CODE REVIEW

**Comment by massakam** [comment]
`Build NAPI macos - Node 18 - arm64` is failing, but it appears to be unrelated to this change.
```
ld: archive has no table of contents file '/Users/runner/work/pulsar-client-node/pulsar-client-node/pkg/mac/build-pulsar/install/lib/libpulsarwithdeps.a' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Failed to execute '/Users/runner/hostedtoolcache/node/18.17.0/x64/bin/node /Users/runner/hostedtoolcache/node/18.17.0/x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --target_arch=arm64 --module=/Users/runner/work/pulsar-client-node/pulsar-client-node/lib/binding/pulsar.node --module_name=pulsar --module_path=/Users/runner/work/pulsar-client-node/pulsar-client-node/lib/binding --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
make: *** [Release/pulsar.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/runner/hostedtoolcache/node/18.17.0/x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 21.6.0
gyp ERR! command "/Users/runner/hostedtoolcache/node/18.17.0/x64/bin/node" "/Users/runner/hostedtoolcache/node/18.17.0/x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--target_arch=arm64" "--module=/Users/runner/work/pulsar-client-node/pulsar-client-node/lib/binding/pulsar.node" "--module_name=pulsar" "--module_path=/Users/runner/work/pulsar-client-node/pulsar-client-node/lib/binding" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
gyp ERR! cwd /Users/runner/work/pulsar-client-node/pulsar-client-node
gyp ERR! node -v v18.17.0
gyp ERR! node-gyp -v v9.3.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/runner/hostedtoolcache/node/18.17.0/x64/bin/node /Users/runner/hostedtoolcache/node/18.17.0/x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --target_arch=arm64 --module=/Users/runner/work/pulsar-client-node/pulsar-client-node/lib/binding/pulsar.node --module_name=pulsar --module_path=/Users/runner/work/pulsar-client-node/pulsar-client-node/lib/binding --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/runner/work/pulsar-client-node/pulsar-client-node/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
node-pre-gyp ERR! System Darwin 21.6.0
node-pre-gyp ERR! command "/Users/runner/hostedtoolcache/node/18.17.0/x64/bin/node" "/Users/runner/work/pulsar-client-node/pulsar-client-node/node_modules/.bin/node-pre-gyp" "build" "--target_arch=arm64"
node-pre-gyp ERR! cwd /Users/runner/work/pulsar-client-node/pulsar-client-node
node-pre-gyp ERR! node -v v18.17.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.11
node-pre-gyp ERR! not ok 
Error: Process completed with exit code 1.
```

**Comment by tisonkun** [comment]
I wrote an executable for doing similar things and it's used in some of Pulsar projects like pulsar-site and pulsar-client-go.

* http://github.com/korandoru/hawkeye

This task should be trivial to implement stably and correctly. (Once it's checked in, there should be no bug to "fix".) I'd propose to switch to my tool if we anyway want to make changes and I'm glad to prepare a patch.

**Comment by tisonkun** [comment]
@massakam Thanks for your explanation! Then my tool doesn't implement that.

**Comment by massakam** [comment]
https://github.com/apache/pulsar-client-node/pull/340#issuecomment-1680303094 seems to have been fixed by https://github.com/apache/pulsar-client-node/pull/341.

**Review by shibd — APPROVED** [review]

**Review by nkurihar — APPROVED** [review]
LGTM

**Pull request merged**
